In [278]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [279]:
df = pd.read_csv('train.txt', sep =';',header = None,names = ['text','emotion'])

In [280]:
print(df['text'].head())

0                              i didnt feel humiliated
1    i can go from feeling so hopeless to so damned...
2     im grabbing a minute to post i feel greedy wrong
3    i am ever feeling nostalgic about the fireplac...
4                                 i am feeling grouchy
Name: text, dtype: object

In [281]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [282]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [283]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [284]:
unique_emotion = df['emotion'].unique()
emotion_number = {}
i =0
for  emo in unique_emotion:
  emotion_number[emo] = i
  i = i+1
df['emotion'] = df['emotion'].map(emotion_number)

In [285]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [286]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [287]:
import string
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [288]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [289]:
df['text'] = df['text'].apply(remove_punc)

In [290]:
def remove_numbers(txt):
   new = ""
   for i in txt:
       if not i.isdigit():
           new = new + i
   return  new
df['text'] = df['text'].apply(remove_numbers)

In [291]:
print(df['text'].head())

0                              i didnt feel humiliated
1    i can go from feeling so hopeless to so damned...
2     im grabbing a minute to post i feel greedy wrong
3    i am ever feeling nostalgic about the fireplac...
4                                 i am feeling grouchy
Name: text, dtype: object

In [292]:
# def remove_emojis(txt):
#    new = ""
#    for i in txt:
#        if not i.isascii():
#            new = new + i
#    return  new
# df['text'] = df['text'].apply(remove_emojis)

In [293]:
print(df['text'].head())

0                              i didnt feel humiliated
1    i can go from feeling so hopeless to so damned...
2     im grabbing a minute to post i feel greedy wrong
3    i am ever feeling nostalgic about the fireplac...
4                                 i am feeling grouchy
Name: text, dtype: object

In [294]:
import nltk

In [295]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [296]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [297]:
stop_words = set(stopwords.words('english'))

In [298]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [299]:
def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if i  not in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

In [300]:
df['text'] =df['text'].apply(remove)

In [301]:
print(df['text'].head())

0                                didnt feel humiliated
1    go feeling hopeless damned hopeful around some...
2            im grabbing minute post feel greedy wrong
3    ever feeling nostalgic fireplace know still pr...
4                                      feeling grouchy
Name: text, dtype: object

In [302]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [303]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df['text'],
    df['emotion'],
    test_size=0.20,
    random_state=42
)

In [304]:
print(X_train.head())
print(X_train.shape)

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
Name: text, dtype: object
(12800,)

In [305]:
print(X_train.head(10).to_list())

print("Total rows:", len(X_train))
print("Empty rows:", X_train.astype(str).str.strip().eq('').sum())
print("NaN rows:", X_train.isna().sum())

['refers course though cant help feeling somehow ironically retrospect loudons son kate mcgarrigle rather talented rufus wainwright', 'im starting feel im suffering fatigue', 'feel like probably would liked book little bit simple story line', 'really feel awkward', 'im feeling little grumpy today lame weather tease got weekend', 'realized ignoring better heartbreaking feel helpless', 'dark chocolate may square im feeling need sweet', 'believe people use fulsome manners social reasons top scale human evolution feel hurt fake behavior', 'feel like less faithful less worthy less loving less able', 'feel peaceful centered endless supply energy day accomplish important']
Total rows: 12800
Empty rows: 0
NaN rows: 0

In [306]:
print(df['text'].iloc[:20].to_list())

['didnt feel humiliated', 'go feeling hopeless damned hopeful around someone cares awake', 'im grabbing minute post feel greedy wrong', 'ever feeling nostalgic fireplace know still property', 'feeling grouchy', 'ive feeling little burdened lately wasnt sure', 'ive taking milligrams times recommended amount ive fallen asleep lot faster also feel like funny', 'feel confused life teenager jaded year old man', 'petronas years feel petronas performed well made huge profit', 'feel romantic', 'feel like make suffering seeing mean something', 'feel running divine experience expect type spiritual encounter', 'think easiest time year feel dissatisfied', 'feel low energy thirsty', 'immense sympathy general point possible proto writer trying find time write corners life sign agent let alone publishing contract feels little precious', 'feel reassured anxiety side', 'didnt really feel embarrassed', 'feel pretty pathetic time', 'started feeling sentimental dolls child began collection vintage barbie dolls sixties', 'feel compromised skeptical value every unit work put']

In [307]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

bow_vectorizer = CountVectorizer()

x_train_bow = bow_vectorizer.fit_transform(X_train)
x_test_bow = bow_vectorizer.transform(X_test)

In [308]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,classification_report, f1_score

In [309]:
nb_model = MultinomialNB()

In [310]:
nb_model.fit(x_train_bow,y_train)

MultinomialNB()

In [311]:
pred_nb = nb_model.predict(x_test_bow)
pred_nb

array([0, 5, 0, ..., 5, 5, 0])

In [312]:
print(accuracy_score(y_test,pred_nb))

0.768125

In [313]:
tfidf_vectorizer = TfidfVectorizer()

In [314]:
x_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
x_test_tfidf = tfidf_vectorizer.transform(X_test)

In [315]:
nb2_model = MultinomialNB()

In [316]:
nb2_model.fit(x_train_tfidf , y_train)

MultinomialNB()

In [317]:
y_pred = nb2_model.predict(x_test_tfidf)

In [318]:
print(accuracy_score(y_test, y_pred))

0.6609375

In [319]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression(max_iter=1000)

In [320]:
logistic_model.fit(x_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [321]:
log_pred = logistic_model.predict(x_test_tfidf)

In [322]:
print(accuracy_score(y_test,log_pred))

0.8628125

In [323]:
from sklearn.svm import LinearSVC

In [324]:
svm_model = LinearSVC()

In [325]:
svm_model.fit(x_train_tfidf, y_train)

LinearSVC()

In [326]:
svm_pred = svm_model.predict(x_test_tfidf)

In [327]:
print(accuracy_score(y_test,svm_pred))

0.891875

In [328]:
from sklearn.linear_model import SGDClassifier

In [329]:
sgd_model = SGDClassifier(random_state=42)
sgd_model.fit(x_train_tfidf, y_train)

SGDClassifier(random_state=42)

In [330]:
sgd_pred = sgd_model.predict(x_test_tfidf)

In [331]:
print(accuracy_score(y_test,sgd_pred))

0.8921875

In [332]:
from sklearn.linear_model import RidgeClassifier

In [333]:
ridge_model = RidgeClassifier()
ridge_model.fit(x_train_tfidf, y_train)

RidgeClassifier()

In [334]:
ridge_pred = ridge_model.predict(x_test_tfidf)

In [335]:
print(accuracy_score(y_test,ridge_pred))

0.889375

In [336]:
from sklearn.naive_bayes import ComplementNB

In [337]:
cnb_model = ComplementNB()
cnb_model.fit(x_train_tfidf, y_train)

ComplementNB()

In [338]:
cnb_pred = cnb_model.predict(x_test_tfidf)

In [339]:
print(accuracy_score(y_test,cnb_pred))

0.885625

In [340]:
from sklearn.ensemble import RandomForestClassifier

In [341]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(x_train_tfidf, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [342]:
rf_pred = rf_model.predict(x_test_tfidf)

In [343]:
print(accuracy_score(y_test,rf_pred))

0.8846875

In [344]:
from sklearn.neighbors import KNeighborsClassifier

In [345]:
knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(x_train_tfidf, y_train)

KNeighborsClassifier()

In [346]:
knn_pred = knn_model.predict(x_test_tfidf)

In [347]:
print(accuracy_score(y_test,knn_pred))

0.7825

In [348]:
results = {
    "Model": [
        "Multinomial Naive Bayes CountVector",
        "Multinomial Naive Bayes TfidfVectorizer",
        "KNN",
        "Logistic Regression",
        "Linear SVM",
        "SGD Classifier",
        "Ridge Classifier",
        "Complement NB",
        "Random Forest"
    ],
    "Accuracy": [
        accuracy_score(y_test, log_pred),
        accuracy_score(y_test, pred_nb),
        accuracy_score(y_test, y_pred),
        accuracy_score(y_test, knn_pred),
        accuracy_score(y_test, svm_pred),
        accuracy_score(y_test, sgd_pred),
        accuracy_score(y_test, ridge_pred),
        accuracy_score(y_test, cnb_pred),
        accuracy_score(y_test, rf_pred)
    ],
    "Macro F1": [
        f1_score(y_test, log_pred, average="macro"),
        f1_score(y_test, pred_nb, average="macro"),
        f1_score(y_test, y_pred, average="macro"),
        f1_score(y_test, knn_pred, average="macro"),
        f1_score(y_test, svm_pred, average="macro"),
        f1_score(y_test, sgd_pred, average="macro"),
        f1_score(y_test, ridge_pred, average="macro"),
        f1_score(y_test, cnb_pred, average="macro"),
        f1_score(y_test, rf_pred, average="macro")
    ]
}

results_df = pd.DataFrame(results)
print(results_df.sort_values(by="Macro F1", ascending=False))

                                     Model  Accuracy  Macro F1
5                           SGD Classifier  0.892188  0.857922
4                               Linear SVM  0.891875  0.857684
8                            Random Forest  0.884687  0.854899
6                         Ridge Classifier  0.889375  0.853753
7                            Complement NB  0.885625  0.849180
0      Multinomial Naive Bayes CountVector  0.862812  0.801440
3                      Logistic Regression  0.782500  0.725910
1  Multinomial Naive Bayes TfidfVectorizer  0.768125  0.600757
2                                      KNN  0.660937  0.402730

In [349]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report

sgd_model = SGDClassifier(
    loss='hinge',
    alpha=0.0001,
    max_iter=1000,
    random_state=42
)

sgd_model.fit(x_train_tfidf, y_train)

sgd_pred = sgd_model.predict(x_test_tfidf)

print("Accuracy:", accuracy_score(y_test, sgd_pred))
print("Macro F1:", f1_score(y_test, sgd_pred, average='macro'))

print(classification_report(y_test, sgd_pred))

Accuracy: 0.8921875
Macro F1: 0.8579222430323634
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       946
           1       0.90      0.89      0.89       427
           2       0.84      0.73      0.78       296
           3       0.87      0.70      0.77       113
           4       0.87      0.85      0.86       397
           5       0.88      0.94      0.91      1021

    accuracy                           0.89      3200
   macro avg       0.88      0.84      0.86      3200
weighted avg       0.89      0.89      0.89      3200

In [350]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import SGDClassifier

In [351]:
model_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('sgd', SGDClassifier(
        loss='hinge',
        alpha=0.0001,
        max_iter=1000,
        random_state=42
    ))
])

In [352]:
model_pipeline.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('sgd', SGDClassifier(random_state=42))])

In [353]:
pipeline_pred = model_pipeline.predict(X_test)

print("Pipeline Accuracy:",
      accuracy_score(y_test, pipeline_pred))

print("Pipeline Macro F1:",
      f1_score(y_test, pipeline_pred, average='macro'))

print(classification_report(y_test, pipeline_pred))

Pipeline Accuracy: 0.8921875
Pipeline Macro F1: 0.8579222430323634
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       946
           1       0.90      0.89      0.89       427
           2       0.84      0.73      0.78       296
           3       0.87      0.70      0.77       113
           4       0.87      0.85      0.86       397
           5       0.88      0.94      0.91      1021

    accuracy                           0.89      3200
   macro avg       0.88      0.84      0.86      3200
weighted avg       0.89      0.89      0.89      3200

In [354]:
print(y_train.value_counts())

emotion
5    4341
0    3720
1    1732
4    1540
2    1008
3     459
Name: count, dtype: int64

In [355]:
print(df.columns)

Index(['text', 'emotion'], dtype='object')

In [356]:
print(df['emotion'].unique())
print(df['emotion'].value_counts())

[0 1 2 3 4 5]
emotion
5    5362
0    4666
1    2159
4    1937
2    1304
3     572
Name: count, dtype: int64

In [357]:
reverse_emotion = {
    v: k for k, v in emotion_number.items()
}

print(reverse_emotion)

{0: 'sadness', 1: 'anger', 2: 'love', 3: 'surprise', 4: 'fear', 5: 'joy'}

In [358]:
text = ["I am very happy today"]

prediction = loaded_model.predict(text)

print("Numeric prediction:", prediction)
print("Emotion:", [reverse_emotion[p] for p in prediction])

Numeric prediction: [5]
Emotion: ['joy']

In [359]:
raw_df = pd.read_csv(
    'train.txt',
    sep=';',
    header=None,
    names=['text', 'emotion']
)

print(raw_df['emotion'].unique())

['sadness' 'anger' 'love' 'surprise' 'fear' 'joy']

In [360]:
unique_emotion = raw_df['emotion'].unique()

emotion_number = {
    emo: i for i, emo in enumerate(unique_emotion)
}

reverse_emotion = {
    v: k for k, v in emotion_number.items()
}

print(reverse_emotion)

{0: 'sadness', 1: 'anger', 2: 'love', 3: 'surprise', 4: 'fear', 5: 'joy'}

In [361]:
text = ["I am very happy today"]

prediction = loaded_model.predict(text)

emotion = [reverse_emotion[int(p)] for p in prediction]

print("Numeric prediction:", prediction)
print("Predicted emotion:", emotion)

Numeric prediction: [5]
Predicted emotion: ['joy']

In [362]:
import joblib

model_data = {
    "model": model_pipeline,
    "reverse_emotion": reverse_emotion
}

joblib.dump(model_data, "NLP_Pipeline.pkl")

['NLP_Pipeline.pkl']

In [371]:
from google.colab import files

files.download("NLP_Pipeline.pkl")